import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

export interface AgreementMember {
  full_name: string | null;
  employee_id_masked: string | null;
  cadre: string | null;
  designation: string | null;
  pay_level: string | null;
  current_state: string | null;
  current_district: string | null;
  current_office: string | null;
  /** Where this member wishes to go (their relevant preference for the swap). */
  desired_state: string | null;
  desired_district: string | null;
}

export interface AgreementInput {
  type: "direct" | "chain";
  members: AgreementMember[];
  generatedOn?: Date;
}

const M = 56; // page margin
const PAGE_W = 595.28; // A4
const PAGE_H = 841.89;

/**
 * Build a pre-filled joint mutual-transfer application as a PDF (pdf-lib, open
 * source — no paid API). Returns raw bytes suitable for a download response.
 */
export async function buildAgreementPdf(input: AgreementInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const generatedOn = input.generatedOn ?? new Date();

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - M;

  const ctx = { doc, page, y, font, bold };

  const heading = input.type === "direct" ? "Joint Application for Mutual Transfer" : "Joint Application for Mutual Transfer (Chain Swap)";
  ctx.y = drawTitle(ctx.page, ctx.bold, heading, ctx.y);

  ctx.y = drawText(ctx, "To,", { gap: 6 });
  ctx.y = drawText(ctx, "The Competent Authority,", {});
  ctx.y = drawText(ctx, "(Establishment / Subordinate Courts),", {});
  ctx.y = drawText(ctx, "____________________________________", { gap: 14 });

  ctx.y = drawText(ctx, `Subject: Request for mutual transfer between the undersigned ${input.members.length} employees.`, { font: bold, gap: 12 });

  ctx.y = drawWrapped(
    ctx,
    "Respected Sir/Madam, the undersigned employees, being similarly placed in cadre, designation and pay level, " +
      "hereby jointly request a mutual transfer (posting swap) as detailed below. Each of us is willing to be relieved " +
      "from our present posting and to assume charge at the posting of the next employee in this arrangement.",
    { gap: 14 }
  );

  // Per-member blocks
  input.members.forEach((m, i) => {
    ensureSpace(ctx, 150);
    ctx.y = drawText(ctx, `Employee ${i + 1}`, { font: bold, gap: 4 });
    ctx.y = drawKV(ctx, "Name", m.full_name);
    ctx.y = drawKV(ctx, "Employee ID (masked)", m.employee_id_masked);
    ctx.y = drawKV(ctx, "Cadre / Establishment", m.cadre);
    ctx.y = drawKV(ctx, "Designation / Post", m.designation);
    ctx.y = drawKV(ctx, "Pay Level / Scale", m.pay_level);
    ctx.y = drawKV(ctx, "Present Posting", joinLoc(m.current_office, m.current_district, m.current_state));
    ctx.y = drawKV(ctx, "Requested Posting", joinLoc(null, m.desired_district, m.desired_state), 8);
  });

  // Swap summary
  ensureSpace(ctx, 80);
  ctx.y = drawText(ctx, "Summary of the proposed swap:", { font: bold, gap: 4 });
  const n = input.members.length;
  input.members.forEach((m, i) => {
    const next = input.members[(i + 1) % n];
    const arrow = `${shortLoc(m.current_district, m.current_state)}  →  ${shortLoc(next.current_district, next.current_state)}`;
    ctx.y = drawText(ctx, `• ${m.full_name ?? `Employee ${i + 1}`}: ${arrow}`, { size: 11 });
  });

  ctx.y -= 8;
  ctx.y = drawWrapped(
    ctx,
    "We confirm that the particulars stated above are true to the best of our knowledge, that we are eligible for " +
      "mutual transfer as per the applicable rules, and that we make this request voluntarily and with mutual consent.",
    { gap: 18 }
  );

  // Signature lines
  ensureSpace(ctx, 60 + n * 16);
  ctx.y = drawText(ctx, "Signatures:", { font: bold, gap: 10 });
  input.members.forEach((m, i) => {
    ensureSpace(ctx, 36);
    drawText(ctx, `__________________________`, { gap: 2 });
    ctx.y = drawText(ctx, `${m.full_name ?? `Employee ${i + 1}`}  (Date: ____________)`, { size: 10, gap: 12 });
  });

  // Disclaimer footer on every page
  const note =
    "Note: This application is generated by a facilitation platform that only helps eligible employees discover one " +
    "another. The actual transfer is subject to verification and approval by the Competent Authority. " +
    `Generated on ${generatedOn.toLocaleDateString("en-IN")}.`;
  const pages = doc.getPages();
  for (const p of pages) {
    p.drawText(wrapToWidth(note, font, 8.5, PAGE_W - 2 * M).join("\n"), {
      x: M,
      y: 34,
      size: 8.5,
      font,
      color: rgb(0.4, 0.4, 0.4),
      lineHeight: 11,
    });
  }

  return doc.save();
}

// ── Low-level drawing helpers ─────────────────────────────────────────────────

interface Ctx {
  doc: PDFDocument;
  page: PDFPage;
  y: number;
  font: PDFFont;
  bold: PDFFont;
}

function drawTitle(page: PDFPage, bold: PDFFont, text: string, y: number): number {
  const size = 16;
  const width = bold.widthOfTextAtSize(text, size);
  page.drawText(text, { x: (PAGE_W - width) / 2, y: y - size, size, font: bold, color: rgb(0.1, 0.15, 0.45) });
  return y - size - 18;
}

function drawText(
  ctx: Ctx,
  text: string,
  opts: { font?: PDFFont; size?: number; gap?: number }
): number {
  const size = opts.size ?? 11.5;
  const f = opts.font ?? ctx.font;
  ctx.page.drawText(text, { x: M, y: ctx.y - size, size, font: f, color: rgb(0.1, 0.1, 0.1) });
  return ctx.y - size - (opts.gap ?? 4);
}

function drawKV(ctx: Ctx, key: string, value: string | null, gap = 3): number {
  const size = 11;
  ctx.page.drawText(`${key}:`, { x: M + 10, y: ctx.y - size, size, font: ctx.bold, color: rgb(0.25, 0.25, 0.25) });
  ctx.page.drawText(value ?? "—", { x: M + 180, y: ctx.y - size, size, font: ctx.font, color: rgb(0.1, 0.1, 0.1) });
  return ctx.y - size - gap;
}

function drawWrapped(ctx: Ctx, text: string, opts: { gap?: number; size?: number }): number {
  const size = opts.size ?? 11.5;
  const lines = wrapToWidth(text, ctx.font, size, PAGE_W - 2 * M);
  for (const line of lines) {
    ensureSpace(ctx, size + 4);
    ctx.page.drawText(line, { x: M, y: ctx.y - size, size, font: ctx.font, color: rgb(0.1, 0.1, 0.1) });
    ctx.y -= size + 3;
  }
  return ctx.y - (opts.gap ?? 0);
}

function ensureSpace(ctx: Ctx, needed: number) {
  if (ctx.y - needed < 56) {
    ctx.page = ctx.doc.addPage([PAGE_W, PAGE_H]);
    ctx.y = PAGE_H - M;
  }
}

function wrapToWidth(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const w of words) {
    const candidate = line ? `${line} ${w}` : w;
    if (font.widthOfTextAtSize(candidate, size) > maxWidth && line) {
      lines.push(line);
      line = w;
    } else {
      line = candidate;
    }
  }
  if (line) lines.push(line);
  return lines;
}

function joinLoc(office: string | null, district: string | null, state: string | null): string {
  return [office, district, state].filter(Boolean).join(", ") || "—";
}
function shortLoc(district: string | null, state: string | null): string {
  return [district, state].filter(Boolean).join(", ") || "—";
}
